import { NativeModules, Platform } from 'react-native';
import { kobitonSDK } from './kobitonSDK';

export type BiometricResult =
  | { success: true }
  | { success: false; reason: 'unsupported' | 'not_enrolled' | 'cancelled' | 'error'; message?: string };

/**
 * The KobitonBiometricModule native module is generated by the withKobitonSDK
 * config plugin for both iOS and Android. It calls Kobiton's drop-in replacements:
 *
 *   iOS    → KobitonLAContext()  (instead of LAContext)
 *   Android → com.kobiton.biometric.BiometricPrompt  (instead of androidx.biometric)
 *
 * This is REQUIRED for Kobiton biometric injection to work. expo-local-authentication
 * uses the stock OS classes internally, which the Kobiton platform cannot intercept.
 *
 * Kobiton injection commands:
 *   driver.execute('mobile:biometrics-authenticate', { result: 'passed' })
 *   driver.execute('mobile:biometrics-authenticate', { result: 'failed' })
 */
const KobitonBiometricModule: {
  isAvailable: () => Promise<boolean>;
  authenticate: (reason: string) => Promise<{ success: boolean; error?: string }>;
} | null = NativeModules.KobitonBiometricModule ?? null;

async function isAvailable(): Promise<boolean> {
  if (Platform.OS === 'web') return false;

  if (KobitonBiometricModule) {
    try {
      return await KobitonBiometricModule.isAvailable();
    } catch {
      return false;
    }
  }

  // Fallback for simulators / web previews where native module isn't loaded
  try {
    const LocalAuthentication = await import('expo-local-authentication');
    const hasHardware = await LocalAuthentication.hasHardwareAsync();
    const isEnrolled = await LocalAuthentication.isEnrolledAsync();
    return hasHardware && isEnrolled;
  } catch {
    return false;
  }
}

async function hasHardware(): Promise<boolean> {
  if (Platform.OS === 'web') return false;

  if (KobitonBiometricModule) {
    try {
      return await KobitonBiometricModule.isAvailable();
    } catch {
      return false;
    }
  }

  try {
    const LocalAuthentication = await import('expo-local-authentication');
    return await LocalAuthentication.hasHardwareAsync();
  } catch {
    return false;
  }
}

/**
 * Authenticate using device biometrics via the Kobiton native module.
 *
 * On a Kobiton device this triggers the OS biometric prompt through
 * KobitonLAContext (iOS) or com.kobiton.biometric.BiometricPrompt (Android),
 * allowing the Kobiton platform to inject a pass or fail result remotely.
 *
 * On simulators or environments without the native module, falls back to
 * expo-local-authentication (biometric injection will not work in this mode).
 */
async function authenticate(reason = 'Sign in to Kobiton Expense Tracker'): Promise<BiometricResult> {
  kobitonSDK.logEvent('biometric_prompt_triggered', 'info', {
    reason,
    platform: Platform.OS,
    source: 'login',
    usingKobitonModule: KobitonBiometricModule != null,
  });

  if (Platform.OS === 'web') {
    kobitonSDK.logEvent('biometric_result', 'warn', {
      result: 'unsupported',
      reason: 'web_platform_no_native_api',
    });
    return {
      success: false,
      reason: 'unsupported',
      message:
        'Biometric authentication requires a real device. ' +
        'When running on a Kobiton device with the Biometric SDK installed, ' +
        'the platform injects the pass or fail signal at the OS level.',
    };
  }

  // ── Preferred path: Kobiton native module ─────────────────────────────────
  if (KobitonBiometricModule) {
    try {
      kobitonSDK.logEvent('biometric_os_prompt_shown', 'info', {
        prompt_message: reason,
        module: 'KobitonBiometricModule',
      });

      const result = await KobitonBiometricModule.authenticate(reason);

      if (result.success) {
        kobitonSDK.logEvent('biometric_result', 'info', { result: 'passed', module: 'KobitonBiometricModule' });
        return { success: true };
      }

      const errMsg = result.error ?? 'Authentication failed';
      if (errMsg.toLowerCase().includes('cancel') || errMsg.toLowerCase().includes('user cancel')) {
        kobitonSDK.logEvent('biometric_result', 'info', { result: 'cancelled' });
        return { success: false, reason: 'cancelled' };
      }

      kobitonSDK.logEvent('biometric_result', 'error', { result: 'failed', error: errMsg });
      return { success: false, reason: 'error', message: errMsg };
    } catch (e) {
      kobitonSDK.logEvent('biometric_result', 'error', {
        result: 'error',
        error: String(e),
        module: 'KobitonBiometricModule',
      });
      return { success: false, reason: 'error', message: String(e) };
    }
  }

  // ── Fallback: expo-local-authentication (no Kobiton injection support) ────
  kobitonSDK.logEvent('biometric_fallback_mode', 'warn', {
    message: 'KobitonBiometricModule not loaded — using expo-local-authentication (Kobiton injection unavailable)',
  });

  try {
    const LocalAuthentication = await import('expo-local-authentication');

    const hardwareAvailable = await LocalAuthentication.hasHardwareAsync();
    if (!hardwareAvailable) {
      kobitonSDK.logEvent('biometric_result', 'warn', { result: 'unsupported', reason: 'no_hardware' });
      return { success: false, reason: 'unsupported', message: 'No biometric hardware found on this device' };
    }

    const enrolled = await LocalAuthentication.isEnrolledAsync();
    if (!enrolled) {
      kobitonSDK.logEvent('biometric_result', 'warn', { result: 'not_enrolled', reason: 'no_biometrics_enrolled' });
      return { success: false, reason: 'not_enrolled', message: 'No biometrics enrolled on this device' };
    }

    kobitonSDK.logEvent('biometric_os_prompt_shown', 'info', { prompt_message: reason });

    const result = await LocalAuthentication.authenticateAsync({
      promptMessage: reason,
      fallbackLabel: 'Use password',
      cancelLabel: 'Cancel',
      disableDeviceFallback: false,
    });

    if (result.success) {
      kobitonSDK.logEvent('biometric_result', 'info', { result: 'passed' });
      return { success: true };
    }

    if (result.error === 'user_cancel' || result.error === 'system_cancel') {
      kobitonSDK.logEvent('biometric_result', 'info', { result: 'cancelled' });
      return { success: false, reason: 'cancelled' };
    }

    kobitonSDK.logEvent('biometric_result', 'error', { result: 'failed', error: result.error ?? 'unknown' });
    return { success: false, reason: 'error', message: result.error };
  } catch (e) {
    kobitonSDK.logEvent('biometric_result', 'error', { result: 'error', error: String(e) });
    return { success: false, reason: 'error', message: String(e) };
  }
}

export const biometricService = { isAvailable, hasHardware, authenticate };
